package com.mindhaven.application.chat;

import java.util.Set;
import org.springframework.stereotype.Component;

/** Retrieval routing only; all ordinary replies are generated by the configured model. */
@Component
public class ConversationIntent {
  public record Decision(String mode) {
    public boolean retrieve() {
      return mode.equals("retrieve");
    }
  }

  private static final Set<String> GREETINGS = Set.of("你好", "您好", "嗨", "hello", "hi", "早上好", "晚上好");
  private static final Set<String> THANKS = Set.of("谢谢", "谢谢你", "好的", "好", "嗯", "嗯嗯");
  private static final Set<String> TOPICS = Set.of("吃饭", "睡觉", "学习", "工作", "旅游");
  private static final Set<String> REFERENCES = Set.of("那怎么办", "那我怎么办", "怎么办", "为什么", "然后呢", "这样呢");

  public Decision decide(String input, boolean hasHistory) {
    String text = input.strip().toLowerCase(java.util.Locale.ROOT).replaceAll("[\\s，。！？!?.,]+", "");
    if (GREETINGS.contains(text)) return new Decision("direct");
    if (THANKS.contains(text)) return new Decision("direct");
    if (TOPICS.contains(text)) {
      // A short answer may answer a previous question. Keep that history, but add no new sources.
      if (hasHistory) return new Decision("conversation");
      return new Decision("clarification");
    }
    if (!hasHistory && REFERENCES.contains(text)) return new Decision("clarification");
    return new Decision("retrieve");
  }
}
