service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    metrics:
      level: none
extensions:
  jaeger_query:
    storage:
      traces: local
    http:
      endpoint: 127.0.0.1:16686
    grpc:
      endpoint: 127.0.0.1:16685
  jaeger_storage:
    backends:
      local:
        memory:
          max_traces: 10000
receivers:
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:4318
processors:
  batch: {}
exporters:
  jaeger_storage_exporter:
    trace_storage: local
