import { test } from 'node:test';
import assert from 'node:assert/strict';
import { useChat } from '../.test-dist/views/chat/useChat.js';
const event = (seq, name, data) => `id: ${seq}\nevent: ${name}\ndata: ${JSON.stringify(data)}\n\n`;
const tick = () => new Promise(resolve => setTimeout(resolve, 0));
test('progress updates before done and retains batched stages', async t => {
  let stream;
  const body = new ReadableStream({ start(c) { stream = c; } });
  const run = { id: 'run', sessionId: 'session', message: '找课程', status: 'RUNNING' };
  t.mock.method(globalThis, 'fetch', async url => url.includes('/events?') ? new Response(body) : new Response(JSON.stringify(url.endsWith('/runs') ? run : [])));
  const chat = useChat();
  chat.sessionId.value = 'session'; chat.draft.value = '找课程';
  const sending = chat.send();
  await tick();
  const send = text => stream.enqueue(new TextEncoder().encode(text));
  send(event(1, 'agent-status', { phase: 'model', label: '理解中', step: 1 }));
  await tick();
  assert.equal(chat.status.value, '理解中');
  assert.equal(chat.activeRun.value, true);
  send(event(10, 'delta', { text: '临时说明' }));
  await tick();
  assert.equal(chat.messages.value.at(-1).content, '临时说明');
  send(event(11, 'answer-reset', {}));
  await tick();
  assert.equal(chat.messages.value.at(-1).content, '');
  send(event(12, 'agent-status', { phase: 'tool', label: '查课程', step: 1 }) + event(13, 'done', { message: { id: 'reply', role: 'assistant', content: '结果', status: 'complete' }, metrics: { id: 'metric' } }) + event(14, 'terminal', { ...run, status: 'COMPLETED' }));
  stream.close(); await sending;
  assert.equal(chat.status.value, '回复已完成');
  assert.deepEqual(chat.agentSteps.value.map(s => s.label), ['理解中', '查课程']);
  assert.equal(chat.activeRun.value, false);
});
